### PR TITLE
fix URI encode issues

### LINKED ISSUE #8: Encoded URI while using `navigator.share`
Hey, firstly thanks for the amazing package.

I noticed that the `url` that I pass to the component via `data` prop is actually URL encoded.
https://github.com/harshzalavadiya/react-web-share/blob/0b3d5ef70c6719e1f7982f88435a14143a6af8af/src/index.tsx#L18 this is the code responsible for the same.

Correct me if I am wrong, there shouldn't be a need to encode the url here. And in fact the package should assume that the URL provided by the user is correct. If not, then it is user's fault.

For example:

I passed this
```js
url: `${window.location.origin}/view`
```
and the URI for the `navigator.share` came out in this format
```
<current_pathname>/encoded(<origin>/view)
```

### PR DESCRIPTION
**Pull request by sudhanshu16**
fixes #8

### CODE REVIEW

File: src/components/icon/index.tsx [hunk 1]
```diff
@@ -19,7 +19,7 @@ export default function Icon({ name, data, onClose }: IconProps) {
 
   return (
     <button
-      onClick={() => e(data.url, data.text, data.title) && onClose()}
+      onClick={() => e(decodeURIComponent(data.url || ""), data.text, data.title) && onClose()}
```
Comment (harshzalavadiya) [inline src/components/icon/index.tsx:22]: empty condition will be taken care initially so no need of `|| ""`

also shouldn't it be `encodeURIComponent` since we want to pass it encoded to our UI?

Comment (harshzalavadiya) [reply src/components/icon/index.tsx:22]: Since in native web share sheet we will pass non encoded URL

**Review by harshzalavadiya — CHANGES_REQUESTED** [review]
@sudhanshu16 thanks for the PR can you check for review comments?

File: src/components/icon/index.tsx (hunk 1 above)
Comment (sudhanshu16) [reply src/components/icon/index.tsx:22]: Yea my bad, must have been the sleep deprivation 😅
About the `|| ""`, I added this because `data.url` is optional in `ShareData` and the ts compiler was throwing compile error. that can be solved by making `url` non-optional

**Comment by harshzalavadiya** [comment]
@sudhanshu16 I have fixed ts warning and this PR is merged
